name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "45 11 * * *"
jobs:
  custom-build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Custom Build
        run: |
          bash build/patch_domestic.sh
          bash build/build_l4d2_block.sh
      - uses: actions/upload-artifact@v4
        with:
          name: custom-build-artifact-${{ github.sha }}-${{ github.run_number }}
          path: source
          if-no-files-found: error
          retention-days: 1
          compression-level: 4
          include-hidden-files: false
  build:
    needs: custom-build
    runs-on: ubuntu-24.04
    steps:
      - name: Download Custom Build
        uses: actions/download-artifact@v4
        with:
          name: custom-build-artifact-${{ github.sha }}-${{ github.run_number }}
          path: custom
      - name: Download Previous Build
        uses: actions/checkout@v4
        with:
          repository: SukkaLab/ruleset.skk.moe
          path: previous-build-${{ github.run_id }}-${{ github.run_number }}
      - name: Grab Building Folder
        id: ramdisk
        run: |
          echo "build_dir=previous-build-${{ github.run_id }}-${{ github.run_number }}/sing-box" >> $GITHUB_OUTPUT
      - name: Remove Upstream's Custom Ruleset
        working-directory: ${{ steps.ramdisk.outputs.build_dir }}
        run: |
          rm -v non_ip/my*.json
      - name: Append Custom Ruleset
        run: |
          cp -rv custom/* ${{ steps.ramdisk.outputs.build_dir }}
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact-${{ github.sha }}-${{ github.run_number }}
          path: ${{ steps.ramdisk.outputs.build_dir }}
          if-no-files-found: error
          retention-days: 1
          compression-level: 4
          include-hidden-files: false
  upload_to_cloudflare_r2:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-artifact-${{ github.sha }}-${{ github.run_number }}
          path: public
      - name: Install sing-box
        run: |
          bash <(curl -fsSL https://sing-box.app/deb-install.sh)
      - name: Compile json rule-set
        run: |
          for json in public/domainset/*.json public/ip/*.json public/non_ip/*.json; do
            echo "Compile rule-set: $json"
            sing-box rule-set compile "$json"
          done
      - uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: public
          destination-dir: ruleset
          keep-file-fresh: true
