name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "45 11 * * *"
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install sing-box
        run: |
          curl -fsSL https://sing-box.app/install.sh | sh

      - name: Download Previous Build
        uses: actions/checkout@v4
        with:
          repository: SukkaLab/ruleset.skk.moe
          path: pre-build

      - name: Remove Upstream's Custom Ruleset
        working-directory: pre-build/sing-box
        run: |
          rm -v non_ip/my*.json

      - name: Prepare public directory
        run: |
          mkdir -pv public/{domainset,ip}

      - name: Custom Build
        run: |
          bash scripts/patch.sh
          bash scripts/build.sh

      - name: Append Custom Ruleset
        run: |
          cp -rv source/* public/

      - name: Compile json to rule-set
        working-directory: public
        run: |
          for json in domainset/*.json ip/*.json; do
            echo "Compile rule-set: $json"
            sing-box rule-set compile "$json"
          done

      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact-${{ github.sha }}-${{ github.run_number }}
          path: public
          if-no-files-found: error
          retention-days: 1
          compression-level: 4
          include-hidden-files: false

  upload_to_cloudflare_r2:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-artifact-${{ github.sha }}-${{ github.run_number }}
          path: public

      - uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: public
          destination-dir: ruleset
          keep-file-fresh: true
